[package]
name = "dota-terrain-mod"
version = "0.1.0"
authors = ["ObsoleteXero"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.10"
regex = "1"
crc = "3"
md-5 = "0.10"